{{- if .Values.dkim.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mail-relay.fullname" . }}-opendkim-config
  labels:
    {{- include "mail-relay.labels" . | nindent 4 }}
data:
  opendkim.conf: |
    # OpenDKIM Configuration

    # Host configuration
    InternalHosts refile:/etc/opendkim/TrustedHosts
    KeyTable refile:/etc/opendkim/KeyTable
    SigningTable refile:/etc/opendkim/SigningTable

    # Process configuration
    pidfile /run/opendkim/opendkim.pid

    # Logging configuration - enable verbose logging to stdout
    Syslog                  no
    LogWhy                  yes
    LogResults              yes

    # Required to use inet socket
    UMask                   002

    # Commonly-used options
    Canonicalization        relaxed/simple
    Mode                    sv
    SubDomains              no

    # TCP Socket for Postfix to connect to
    Socket                  inet:8891@localhost

    # Additional security options
    RequireSafeKeys         false

  TrustedHosts: |
{{- include "mail-relay.trustedHosts" . | nindent 4 }}

  KeyTable: |
{{- include "mail-relay.dkimKeyTable" . | nindent 4 }}

  SigningTable: |
{{- include "mail-relay.dkimSigningTable" . | nindent 4 }}
{{- end }}
