apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mail-relay.fullname" . }}-rsyslog
  labels:
    {{- include "mail-relay.labels" . | nindent 4 }}
data:
  rsyslog.conf: |
    # /etc/rsyslog.conf configuration file for rsyslog
    #
    # For more information install rsyslog-doc and see
    # /usr/share/doc/rsyslog-doc/html/configuration/index.html
    #
    # Default logging rules can be found in /etc/rsyslog.d/50-default.conf

    #################
    #### MODULES ####
    #################

    # provides --MARK-- message capability
    module(load="immark")

    # provides UDP syslog reception
    #module(load="imudp")
    #input(type="imudp" port="514")

    # provides TCP syslog reception
    #module(load="imtcp")
    #input(type="imtcp" port="514")

    # Note: Disable imklog module as it requires access to /proc/kmsg
    # which is not available in Kubernetes containers
    # module(load="imklog")

    ###########################
    #### GLOBAL DIRECTIVES ####
    ###########################

    #
    # Use traditional timestamp format.
    # To enable high precision timestamps, comment out the following line.
    #
    $ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

    # Filter duplicated messages
    $RepeatedMsgReduction on

    #
    # Set the default permissions for all log files.
    #
    $FileOwner syslog
    $FileGroup adm
    $FileCreateMode 0640
    $DirCreateMode 0755
    $Umask 0022
    $PrivDropToUser syslog
    $PrivDropToGroup syslog

    #
    # Where to place spool files
    #
    $WorkDirectory /var/spool/rsyslog

    #
    # Include all config files in /etc/rsyslog.d/
    #
    $IncludeConfig /etc/rsyslog.d/*.conf

    ###############
    #### RULES ####
    ###############

    # Log anything (except mail) of level info or higher.
    # Don't log private authentication messages!
    *.info;mail.none;authpriv.none;cron.none    /var/log/messages

    # The authpriv file has restricted access.
    authpriv.*                                  /var/log/secure

    # Log all the mail messages in one place.
    mail.*                                      /var/log/maillog

    # Log cron stuff
    cron.*                                      /var/log/cron

    # Everybody gets emergency messages
    *.emerg                                     :omusrmsg:*

    # Save news errors of level crit and higher in a special file.
    uucp,news.crit                              /var/log/spooler

    # Save boot messages also to boot.log
    local7.*                                    /var/log/boot.log

    # Enhanced logging for mail services to stdout with better formatting
    # Postfix logs (mail facility)
    mail.info                                   /dev/stdout

    # Daemon logs (includes OpenDKIM)
    daemon.*                                    /dev/stdout

    # Send all logs to console as well for container visibility
    *.* /dev/stdout
