{{- if .Values.dkim.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mail-relay.fullname" . }}-opendkim-config
  labels:
    {{- include "mail-relay.labels" . | nindent 4 }}
data:
  opendkim.conf: |
    # OpenDKIM Configuration - Based on working Gmail-compatible setup

    # Host and table configuration
    InternalHosts refile:/etc/opendkim/TrustedHosts
    KeyTable refile:/etc/opendkim/KeyTable
    SigningTable refile:/etc/opendkim/SigningTable

    # Process configuration
    pidfile /run/opendkim/opendkim.pid

    # Log to syslog
    Syslog                  no
    LogResults             yes
    LogWhy                 yes

    # Required to use local socket with MTAs that access the socket as a non-
    # privileged user (e.g. Postfix)
    UMask                   002

    # Commonly-used options
    Canonicalization        relaxed/simple
    Mode                    sv
    SubDomains              no

    # Socket for Postfix to connect to
    Socket                  inet:8891@localhost

  TrustedHosts: |
{{- include "mail-relay.trustedHosts" . | nindent 4 }}

  KeyTable: |
{{- include "mail-relay.dkimKeyTable" . | nindent 4 }}

  SigningTable: |
{{- include "mail-relay.dkimSigningTable" . | nindent 4 }}
{{- end }}
