{{- if and .Values.externalDns.enabled .Values.externalDns.autoManageDnsRecords }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mail-relay.fullname" . }}-dnsendpoint-template
  labels:
    {{- include "mail-relay.labels" . | nindent 4 }}
data:
  dnsendpoint-template.yaml: |
    apiVersion: externaldns.k8s.io/v1alpha1
    kind: DNSEndpoint
    metadata:
      name: {{ .Release.Name }}-dns
      namespace: {{ .Release.Namespace }}
      annotations:
        external-dns.alpha.kubernetes.io/owner-id: {{ .Values.externalDns.ownerId | quote }}
      labels:
        app.kubernetes.io/name: {{ include "mail-relay.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "mail-relay.chart" . }}
    spec:
      endpoints:
      # A Record for mail server
      - dnsName: {{ .Values.mail.hostname }}
        recordTTL: {{ .Values.externalDns.ttl }}
        recordType: A
        targets: ["${CURRENT_IP}"]
{{- range $index, $domain := .Values.mail.domains }}
      # MX Record for {{ $domain.name }}
      - dnsName: {{ $domain.name }}
        recordTTL: {{ $.Values.externalDns.ttl }}
        recordType: MX
        targets: ["10 {{ $.Values.mail.hostname }}"]
      # SPF Record for {{ $domain.name }}
      - dnsName: {{ $domain.name }}
        recordTTL: {{ $.Values.externalDns.ttl }}
        recordType: TXT
        targets: ["\"v=spf1 ip4:${CURRENT_IP} a:{{ $.Values.mail.hostname }} ~all\""]
      # DMARC Record for {{ $domain.name }}
      - dnsName: _dmarc.{{ $domain.name }}
        recordTTL: {{ $.Values.externalDns.ttl }}
        recordType: TXT
        targets: ["\"{{ $.Values.externalDns.dmarcPolicy }}\""]
{{- if and $.Values.dkim.enabled $.Values.dkim.autoGenerate }}
      # DKIM Record for {{ $domain.name }}
      - dnsName: {{ $.Values.dkim.selector | default "mail" }}._domainkey.{{ $domain.name }}
        recordTTL: {{ $.Values.externalDns.ttl }}
        recordType: TXT
        targets: ["\"${DKIM_RECORD_{{ $index }}}\""]
{{- end }}
{{- end }}
{{- end }}
