apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mail-relay.fullname" . }}-postfix-config
  labels:
    {{- include "mail-relay.labels" . | nindent 4 }}
data:
  main.cf: |
    # Basic configuration
    myhostname = {{ .Values.mail.hostname }}
    mydomain = {{ .Values.mail.hostname }}
    myorigin = $mydomain

    # Network and interface configuration
    inet_interfaces = all
    inet_protocols = ipv4

    # Logging configuration - direct to stdout for containers
    maillog_file = /dev/stdout

    # Relay configuration - disable local delivery, relay only
    {{- if .Values.mail.relayHost }}
    relayhost = {{ .Values.mail.relayHost }}:{{ .Values.mail.relayPort }}
    {{- else }}
    relayhost =
    {{- end }}

    # Disable local delivery completely
    mydestination =
    local_recipient_maps =
    local_transport = error:local delivery is disabled

    # Trusted networks configuration
    mynetworks = {{ range .Values.mail.trustedNetworks }}{{ . }}, {{ end }}{{ range .Values.mail.trustedIPs }}{{ . }}, {{ end }}127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128

    {{- if and .Values.mail.relayCredentials.enabled .Values.mail.relayHost }}
    # SASL authentication for relay
    smtp_sasl_auth_enable = yes
    smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
    smtp_sasl_security_options = noanonymous
    smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
    smtp_use_tls = yes
    {{- end }}

    # DKIM configuration
    {{- if .Values.dkim.enabled }}
    milter_default_action = accept
    milter_protocol = 2
    smtpd_milters = inet:127.0.0.1:8891
    non_smtpd_milters = inet:127.0.0.1:8891
    milter_macro_daemon_name = ORIGINATING
    {{- end }}

    # TLS settings
    smtp_tls_security_level = may

    # Logging configuration
    {{- if eq .Values.mail.logDestination "file" }}
    maillog_file = /var/log/mail.log
    {{- else }}
    maillog_file = /dev/stdout
    maillog_file_prefixes = /dev
    {{- end }}

    # Relay restrictions
    smtpd_relay_restrictions = permit_mynetworks, reject_unauth_destination

    # Header checks
    {{- if .Values.mail.headerChecks.enabled }}
    header_checks = regexp:/etc/postfix/header_checks
    {{- end }}

    # Sender restrictions with optional sender access control
    {{- if and .Values.mail.senderAccess .Values.mail.senderAccess.enabled }}
    smtpd_sender_restrictions = check_sender_access hash:/etc/postfix/sender_access, reject_non_fqdn_sender, reject_unknown_sender_domain, permit
    {{- else }}
    smtpd_sender_restrictions = permit_mynetworks, reject_non_fqdn_sender, reject_unknown_sender_domain, permit
    {{- end }}

    # Message size limit
    message_size_limit = {{ .Values.mail.messageSizeLimit | default "50MB" | replace "MB" "000000" | replace "KB" "000" | replace "GB" "000000000" }}

    # Additional security settings
    smtpd_banner = $myhostname ESMTP
    disable_vrfy_command = yes
    smtpd_helo_required = yes
    smtpd_helo_restrictions = permit_mynetworks, reject_invalid_helo_hostname, permit
    smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination, permit

    # Compatibility settings
    compatibility_level = 3.6

    # Queue settings
    maximal_queue_lifetime = 1d
    bounce_queue_lifetime = 1d

    # DNS resolver settings for containerized environments
    smtp_dns_support_level = enabled
    smtp_host_lookup = dns

  master.cf: |
    #
    # Postfix master process configuration file.  For details on the format
    # of the file, see the master(5) manual page (command: "man 5 master" or
    # on-line: http://www.postfix.org/master.5.html).
    #
    # Do not forget to execute "postfix reload" after editing this file.
    #
    # ==========================================================================
    # service type  private unpriv  chroot  wakeup  maxproc command + args
    #               (yes)   (yes)   (no)    (never) (100)
    # ==========================================================================
    smtp      inet  n       -       y       -       -       smtpd
    {{ .Values.service.ports.smtp.port }}      inet  n       -       y       -       -       smtpd
    pickup    unix  n       -       y       60      1       pickup
    cleanup   unix  n       -       y       -       0       cleanup
    qmgr      unix  n       -       n       300     1       qmgr
    tlsmgr    unix  -       -       y       1000?   1       tlsmgr
    rewrite   unix  -       -       y       -       -       trivial-rewrite
    bounce    unix  -       -       y       -       0       bounce
    defer     unix  -       -       y       -       0       bounce
    trace     unix  -       -       y       -       0       bounce
    verify    unix  -       -       y       -       1       verify
    flush     unix  n       -       y       1000?   0       flush
    proxymap  unix  -       -       n       -       -       proxymap
    proxywrite unix -       -       n       -       1       proxymap
    smtp      unix  -       -       n       -       -       smtp
    relay     unix  -       -       y       -       -       smtp
            -o syslog_name=postfix/$service_name
    showq     unix  n       -       y       -       -       showq
    error     unix  -       -       y       -       -       error
    retry     unix  -       -       y       -       -       error
    discard   unix  -       -       y       -       -       discard
    local     unix  -       n       n       -       -       local
    virtual   unix  -       n       n       -       -       virtual
    lmtp      unix  -       -       y       -       -       lmtp
    anvil     unix  -       -       y       -       1       anvil
    scache    unix  -       -       y       -       1       scache
    postlog   unix-dgram n  -       n       -       1       postlogd

    # External delivery methods
    uucp      unix  -       n       n       -       -       pipe
      flags=Fqhu user=uucp argv=uux -r -n -z -a$sender - $nexthop!rmail ($recipient)

  {{- if .Values.mail.headerChecks.enabled }}
  header_checks: |
    {{- if .Values.mail.headerChecks.ignoreForeignReceivedHeaders }}
    # Simple header cleaning rules
    /^Received:\s+from\s+localhost/ OK
    /^Received:\s+from\s+{{ .Values.mail.hostname | replace "." "\\." }}/ OK
    {{- range .Values.mail.domains }}
    /^Received:\s+from\s+.*{{ .name | replace "." "\\." }}/ OK
    {{- end }}
    {{- end }}
    {{- range .Values.mail.headerChecks.rules }}
    {{ tpl .pattern $ }} {{ .action }}
    {{- end }}
  {{- end }}

  {{- if and .Values.mail.relayCredentials.enabled .Values.mail.relayCredentials.username .Values.mail.relayCredentials.password }}
  sasl_passwd: |
    {{ .Values.mail.relayHost }}:{{ .Values.mail.relayPort }} {{ .Values.mail.relayCredentials.username }}:{{ .Values.mail.relayCredentials.password }}
  {{- end }}

  {{- if and .Values.mail.senderAccess .Values.mail.senderAccess.enabled }}
  sender_access: |
    {{- range .Values.mail.senderAccess.allowedSenders }}
    {{ . }} OK
    {{- end }}
    {{- range .Values.mail.senderAccess.rejectedSenders }}
    {{ . }} REJECT
    {{- end }}
  {{- end }}
