apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mail-relay.fullname" . }}-supervisor-config
  labels:
    {{- include "mail-relay.labels" . | nindent 4 }}
data:
  supervisord.conf: |
    [supervisord]
    nodaemon=true
    user=root
    logfile=/var/log/supervisord.log
    pidfile=/var/run/supervisord.pid
    childlogdir=/var/log/supervisor
    loglevel=info

    [unix_http_server]
    file=/var/run/supervisor.sock
    chmod=0700

    [supervisorctl]
    serverurl=unix:///var/run/supervisor.sock

    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

    # OpenDKIM - DKIM signing service (logs to stdout/stderr)
    [program:opendkim]
    command=/usr/sbin/opendkim -f -v
    autostart=%(ENV_DKIM_ENABLED)s
    autorestart=true
    priority=100
    user=opendkim
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    startsecs=3
    stopwaitsecs=10
    directory=/

    # Postfix - main SMTP service (logs directly to stdout)
    [program:postfix]
    command=/usr/sbin/postfix start-fg
    autostart=true
    autorestart=true
    priority=200
    user=root
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    startsecs=5
    stopwaitsecs=30
    stopsignal=TERM

    # Process groups for easier management
    [group:mail-services]
    programs=postfix
    priority=999

    [group:optional-services]
    programs=opendkim
    priority=999
