{{- /*
Refactored: Post-install/upgrade job to ensure DNSEndpoint exists/updated.
Uses shared script (configmap-dns-manager-script) to avoid duplication with cron.
Always runs on install/upgrade. If ipDetection=true the script will detect current IP; else uses all configured external IPs.
*/ -}}
{{- $ipDetection := eq (include "mail-relay.dnsHelper.ipDetection" .) "true" -}}
{{- $externalIps := .Values.dnsHelper.externalIps | default (list) -}}
{{- if and .Values.externalDns.enabled .Values.externalDns.autoManageDnsRecords }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mail-relay.fullname" . }}-dnsendpoint-applier
  labels:
    {{- include "mail-relay.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "15"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "mail-relay.selectorLabels" . | nindent 8 }}
        job: dnsendpoint-applier
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "mail-relay.serviceAccountName" . }}
      containers:
      - name: dnsendpoint-applier
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["/bin/bash","-c","/scripts/manage-dns.sh job"]
        volumeMounts:
        - name: dnsendpoint-template
          mountPath: /etc/dns-template
          readOnly: true
        - name: dns-helper
          mountPath: /scripts
          readOnly: true
        {{- if .Values.persistence.enabled }}
        - name: data
          mountPath: /data
        {{- end }}
      volumes:
      - name: dnsendpoint-template
        configMap:
          name: {{ include "mail-relay.fullname" . }}-dnsendpoint-template
      - name: dns-helper
        configMap:
          name: {{ include "mail-relay.fullname" . }}-dns-helper
          defaultMode: 0755
      {{- if .Values.persistence.enabled }}
      - name: data
        {{- if .Values.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "mail-relay.fullname" . }}-data
        {{- end }}
      {{- else }}
      - name: data
        emptyDir: {}
      {{- end }}
{{- end }}
