{{- if .Values.dkim.enabled }}
{{- range $index, $domain := .Values.mail.domains }}
{{- if $domain.dkim }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mail-relay.fullname" $ }}-dkim-{{ $domain.name | replace "." "-" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "mail-relay.labels" $ | nindent 4 }}
    app.kubernetes.io/component: dkim
    mail-relay.io/domain: {{ $domain.name | quote }}
  annotations:
    {{- if $.Values.dkim.autoGenerate }}
    "helm.sh/resource-policy": keep
    {{- end }}
type: Opaque
data:
  private.key: {{ $domain.dkim.privateKey | b64enc | quote }}
  public.key: {{ $domain.dkim.publicKey | b64enc | quote }}
  dns.record: {{ $domain.dkim.dnsRecord | b64enc | quote }}
  selector: {{ ($domain.dkim.selector | default ($domain.dkimSelector | default "mail")) | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
