{{- if .Values.dkim.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mail-relay.fullname" . }}-opendkim-config
  labels:
    {{- include "mail-relay.labels" . | nindent 4 }}
data:
  opendkim.conf: |
    # OpenDKIM Configuration

    # Log to syslog
    Syslog yes
    SyslogSuccess yes
    LogWhy yes

    # Common settings
    Canonicalization relaxed/simple
    ExternalIgnoreList refile:/etc/opendkim/TrustedHosts
    InternalHosts refile:/etc/opendkim/TrustedHosts
    KeyTable refile:/etc/opendkim/KeyTable
    SigningTable refile:/etc/opendkim/SigningTable
    Mode sv
    PidFile /var/run/opendkim/opendkim.pid
    SignatureAlgorithm rsa-sha256
    UserID opendkim:opendkim
    Socket inet:8891@localhost

    # Key settings
    KeyFile /etc/opendkim/keys/default.private
    Selector {{ (index .Values.mail.domains 0).dkimSelector | default "mail" }}
    Domain {{ .Values.mail.hostname }}

    # Security settings
    RequireSafeKeys yes

    # Performance
    DNSTimeout 5

    # Debugging (adjust as needed)
    LogLevel info

  TrustedHosts: |
{{- include "mail-relay.trustedHosts" . | nindent 4 }}

  KeyTable: |
{{- include "mail-relay.dkimKeyTable" . | nindent 4 }}

  SigningTable: |
{{- include "mail-relay.dkimSigningTable" . | nindent 4 }}
{{- end }}
